name: github pages

on:
  push:
    branches:
    - blog  # default branch

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.3
      with:
        hugo-version: '0.58.3'

    - name: Build
      run: |
            
          hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.xiaoheiah_secret }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
